### ISSUE TITLE
non-contiguous

### ISSUE THREAD

**Issue by 964918993** [lightaime/sgas#9]
I have run the env_install step by step, But when I run the code "sgas/gcn_point/main_modelnet.py", I have the error:
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

Can you help me? Thanks!

**Comment by guochengqian** [comment]
Hello. @964918993  Could you provide more details. For example, in which line did you encounter such an error? 
Since I cannot reproduce the error, it is hard for me to help you. 
Also, you can try to add contiguous here (L81 in gcn/gcn_lib/dense/torch_nn.py):
`idx = idx.view(batch_size, -1)` 
to 
`idx = idx.contiguous().view(batch_size, -1)` 

I hope this will work in your situation. We did not add contiguous() here for the reason that we never met the same issue.

**Comment by guochengqian** [comment]
I add `.contiguous()` in torch_nn.py as default, since more people report the `non-contiguous input` issue. 
The code works fine on my side (V100, Titan XP, Titan V), with PyTorch 1.4 and CUDA10.0. 

If it does not work for you, you guys can reopen the issue and post your environment here, such that we can easily debug and solve the problem together. 

Thanks!

**Comment by 964918993** [comment]
Thanks for your reply.

But the problem I have now is：RuntimeError: No such operator torch_cluster::random_walk.
I have run the env_install step by step, But when I run the code "sgas/gcn_point/train_search", I have  this.

Do you have any thoughts on this question?

**Comment by linhaojia13** [comment]
Hi, @guochengqian . Adding .contiguous() in torch_nn.py as default doesn't work on my side (2080Ti, PyTorch 1.4.0, CUDA 10.1).
Therefore, I disable the cudnn by setting "cudnn.enabled = False" and the time consume for one training epoch is about 84 seconds for training the compact model on ModelNet40.
 I want to know how this disabling can influence the computing speed, could you please tell me your one-epoch training time on the same experiment？
